### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by VantorreWannes** [jimbertools/volmgmt#1]
## Todo

- [x] Add a `.github/ISSUE_TEMPLATE` folder to the project.
- [x] Correctly implement a  `.github/ISSUE_TEMPLATE/config.yml` file.
- [x] Add a feature request config file.
- [ ] Add a bug report config file.
- [ ] Add a hotfix config file.
