### ISSUE TITLE
[Hotfix]: monitor-buffer

### ISSUE THREAD

**Issue by VantorreWannes** [jimbertools/volmgmt#3]
### Description

Hotfix Monitor buffer being too small

### Todo

- [ ] Convert the static buffer in Monitor.run to a dynamically allocated array.

### Definition Of Done

- [ ] Did you create a new branch?
- [ ] Did you commit after each major change?
- [ ] Did you complete all steps outlined in this issue?
- [ ] Did you make a pull request to merge with the dev branch?
