### ISSUE TITLE
[Refactor]: Rename library 

### ISSUE THREAD

**Issue by VantorreWannes** [jimbertools/volmgmt#5]
### Description

Rename library to not conflict with the original repo.

### Todo

- [x] Adjust the name in `go.mod` to [github.com/jimbertools/volmgmt](https://github.com/jimbertools/volmgmt)
- [x] Adjust imports to use new name.

### Definition Of Done

- [x] Did you create a new branch?
- [x] Did you commit after each major change?
- [x] Did you complete all steps outlined in this issue?
- [x] Did you make a pull request to merge with the dev branch?
